/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.atm.android.audiotomidi;

public final class R {
    public static final class array {
        public static final int bufferSizeArray=0x7f050012;
        public static final int bufferSizeValues=0x7f050013;
        public static final int onsetType2Array=0x7f05000c;
        public static final int onsetType2Values=0x7f05000d;
        public static final int onsetTypeArray=0x7f05000a;
        public static final int onsetTypeValues=0x7f05000b;
        public static final int overlapSizeArray=0x7f050014;
        public static final int overlapSizeValues=0x7f050015;
        public static final int pitchTypeArray=0x7f050008;
        public static final int pitchTypeValues=0x7f050009;
        public static final int recChanArray=0x7f050006;
        public static final int recChanValues=0x7f050007;
        public static final int recFormatArray=0x7f050002;
        public static final int recFormatValues=0x7f050003;
        public static final int recFreqArray=0x7f050004;
        public static final int recFreqValues=0x7f050005;
        public static final int silenceArray=0x7f050010;
        public static final int silenceValues=0x7f050011;
        public static final int synthInstrumentArray=0x7f050000;
        public static final int synthInstrumentValues=0x7f050001;
        public static final int thresholdArray=0x7f05000e;
        public static final int thresholdValues=0x7f05000f;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int mic_32x32=0x7f020001;
        public static final int play_32x32=0x7f020002;
        public static final int saxophone_32x32=0x7f020003;
        public static final int saxophone_64x64=0x7f020004;
        public static final int stop_32x32=0x7f020005;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
    }
    public static final class xml {
        public static final int settings=0x7f040000;
    }
}
